name: Build and test
run-name: "Unit testing branch '${{ github.ref_name }}'"

on:
  push:
    branches-ignore:
      - master

env:
  DOTNET_CORE_VERSION: 8.0.x
  
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Start Azure Cosmos DB emulator
        run: |
          Write-Host "Launching Cosmos DB Emulator"
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
          Start-CosmosDbEmulator
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Restore
        run: dotnet restore
      - name: Test
        run: dotnet test